const reviewWrap = document.getElementById("reviewWrap");
const leftArrow = document.getElementById("leftArrow");
const rightArrow = document.getElementById("rightArrow");
const imgDiv = document.getElementById("imgDiv");
const personName = document.getElementById("personName");
const profession = document.getElementById("profession");
const description = document.getElementById("description");
const surpriseMeBtn = document.getElementById("surpriseMeBtn");
const chicken = document.querySelector(".chicken");

let isChickenVisible;

let people = [
  {
    photo:
      'url("https://cdn-icons-png.flaticon.com/256/2920/2920045.png")',
    name: "Chamindi. J. Thewarapperuma",
    profession: "Agriculture Research and Production Assistant, Department of Agrarian Development",
    description:
      "“Your app showcases remarkable innovation in addressing real-world challenges faced by farmers. It's impressive to see how you've utilized technology to make a positive impact on the agricultural sector. That sounds like a fantastic initiative! Your 'Govisewana' web application serves a crucial purpose in empowering farmers with valuable insights into future crop prices and yields. By providing farmers with predictions on future crop prices and yields based on the extent they hope to cultivate, 'Govisewana' empowers them to make informed decisions about their farming practices. This information can significantly impact their planning and financial management. With the ability to foresee potential crop prices and yields, farmers can better mitigate risks associated with fluctuating market conditions and unforeseen challenges. The output generated by 'Govisewana' enables farmers to effectively plan their finances by projecting the income they can expect from their crop yields. The utilization of technology in agriculture through platforms like 'Govisewana' showcases the potential of digital solutions to revolutionize traditional practices. It encourages farmers to embrace technological advancements for improved efficiency and competitiveness. Overall, Govisewana plays a vital role in enhancing the livelihoods of farmers by equipping them with valuable insights and tools to navigate the complexities of agricultural markets and production. It's a commendable effort towards advancing agricultural sustainability and prosperity. The launch of your 'Govisewana' app is just the beginning of what promises to be a journey filled with growth and success. I'm excited to see how you continue to refine and expand your app to serve an even larger audience and make an even greater difference in the agricultural community. Keep up the fantastic work, and congratulations on the successful launch of your Agricultural app!”"
  },

  {
    photo:
      "url('https://cdn-icons-png.flaticon.com/512/436/436299.png')",
    name: "D D Somachandra Kahagolla",
    profession: "Retired Deputy Director (Research) Regional Agricultural Research and Development Centre Bandarawela, Technical Director, Modern Agri (Pvt) Ltd",
    description:
      "“Thank you for sharing your thoughts! Developing a web application to predict price fluctuations for key crops as cabbage, leeks, carrots, and potatoes sounds like a valuable tool for farmers. By providing insights into the best times for cultivation, it can indeed help them plan their farming activities more effectively and potentially mitigate the impact of price fluctuations. To further increase the usefulness, it is better to gather historical price data for these crops in the specific area of interest. This data can then be used to train predictive models that take into account various factors influencing price fluctuations, such as seasonality, weather conditions, market demand, and supply chain dynamics. Additionally, incorporating features like customizable alerts or notifications can further empower farmers to make informed decisions based on the predicted price trends. The web application you have developed is well-organized and easy to navigate, even for those with minimal computer literacy. The inclusion of general cultivation guidelines within the program is also a commendable idea. Developing such a platform to assist farmers in theibusiness endeavours is indeed a valuable initiative.”"
  },

  {
    photo:
      "url('https://cdn-icons-png.flaticon.com/512/436/436299.png')",
    name: "Rasika Fernando",
    profession: "",
    description:
      "“Highly recommend the software developed to address the pressing issues farmers and consumers face in Sri Lanka's agricultural sector. The features outlined in the software demonstrate a comprehensive approach to tackling the challenges prevalent in the industry. This is the current real issue being faced in Sri Lanka, ex:- a couple of months back, bean prices went up to Rs.800/kg and carrot Rs.2500/kg due to the shortage of these crops in the market(underproduction), and consumers suffered greatly. With the production surplus, bean prices dropped to Rs.150/kg and carrot prices to Rs.450/kg. This has been a common issue faced by Sri Lankan farmers for the last decade, and this app is inherent in Sri Lanka (like the weather patterns, extent grown, and prices). Furthermore, currently, there's no solution/ app for this issue. Here's why I believe this software is an excellent solution: Comprehensive Dashboard: Including various features such as yield predictions, demand-supply balance, crop recommendations, and price forecasts in a single dashboard provides farmers with a holistic view of their operations. This enables farmers to make informed decisions efficiently through Crop Yield Prediction, Demand-Supply Analysis., Crop Recommendations, Price Forecasting, Language Accessibility, and Cultivation Guidance. Its comprehensive approach makes it a valuable solution for optimizing agricultural practices, reducing wastage, and improving economic outcomes for both farmers and consumers. I strongly recommend its adoption and utilization to drive positive change in the agriculture industry.”"
  },

];

imgDiv.style.backgroundImage = people[0].photo;
personName.innerText = people[0].name;
profession.innerText = people[0].profession;
description.innerText = people[0].description;
let currentPerson = 0;

//Select the side where you want to slide
function slide(whichSide, personNumber) {
  let reviewWrapWidth = reviewWrap.offsetWidth + "px";
  let descriptionHeight = description.offsetHeight + "px";
  //(+ or -)
  let side1symbol = whichSide === "left" ? "" : "-";
  let side2symbol = whichSide === "left" ? "-" : "";

  let tl = gsap.timeline();

  if (isChickenVisible) {
    tl.to(chicken, {
      duration: 0.4,
      opacity: 0
    });
  }

  tl.to(reviewWrap, {
    duration: 0.4,
    opacity: 0,
    translateX: `${side1symbol + reviewWrapWidth}`
  });

  tl.to(reviewWrap, {
    duration: 0,
    translateX: `${side2symbol + reviewWrapWidth}`
  });

  setTimeout(() => {
    imgDiv.style.backgroundImage = people[personNumber].photo;
  }, 400);
  setTimeout(() => {
    description.style.height = descriptionHeight;
  }, 400);
  setTimeout(() => {
    personName.innerText = people[personNumber].name;
  }, 400);
  setTimeout(() => {
    profession.innerText = people[personNumber].profession;
  }, 400);
  setTimeout(() => {
    description.innerText = people[personNumber].description;
  }, 400);

  tl.to(reviewWrap, {
    duration: 0.4,
    opacity: 1,
    translateX: 0
  });

  if (isChickenVisible) {
    tl.to(chicken, {
      duration: 0.4,
      opacity: 1
    });
  }
}

function setNextCardLeft() {
  if (currentPerson === 2) {
    currentPerson = 0;
    slide("left", currentPerson);
  } else {
    currentPerson++;
  }

  slide("left", currentPerson);
}

function setNextCardRight() {
  if (currentPerson === 0) {
    currentPerson = 2;
    slide("right", currentPerson);
  } else {
    currentPerson--;
  }

  slide("right", currentPerson);
}

leftArrow.addEventListener("click", setNextCardLeft);
rightArrow.addEventListener("click", setNextCardRight);


window.addEventListener("resize", () => {
  description.style.height = "100%";
});